### ISSUE TITLE
Week 07 - Day 1 - Spit and Polish

### ISSUE THREAD

**Issue by gstark** [ooeygg/assignments#23]
Your GitHub repository will be part of your portfolio and you will likely link to it from your portfolio.

Creating a clean looking README is as important for a project as having nice clean code.

Here are some examples of great READMEs:
- [https://github.com/axios/axios](https://github.com/axios/axios)
- [https://github.com/Microsoft/vscode](https://github.com/Microsoft/vscode)
- [https://github.com/twbs/bootstrap](https://github.com/twbs/bootstrap)
- [https://github.com/electron/electron](https://github.com/electron/electron)

Here are some example of great student READMEs:
- [https://github.com/cfsanderson/Minesweeper](https://github.com/cfsanderson/Minesweeper)
- [https://github.com/m1g/tic-react-toe](https://github.com/m1g/tic-react-toe)
- [https://github.com/m1g/snowman](https://github.com/m1g/snowman)

## Objectives

- Create quality READMEs

### Explorer Mode

- [ ] Choose several (at least three) repositories to update the READMEs
- [ ] Include a description, in your own words, of what the assignment was
- [ ] Include a list of technologies (and links to the homepage for each) you used
- [ ] Include a link to the project in production (surge, etc.)
- [ ] Include a screenshot or an animated gif (see https://github.com/wulkano/kap or http://recordit.co/ or https://www.cockos.com/licecap/)
- Optional:
  - [ ] Include an aspect you are particularly proud of
  - [ ] Include a snippet of code you are proud of (see GitHub Markdown on how to format code snippets)

**Comment by ooeygg** [comment]
https://github.com/Myenny/crypto-tracker/blob/master/README.md 
https://github.com/Myenny/reactified-octocats
https://github.com/Myenny/minesweeper

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![Yas](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--eb161dfb00865249fe33bc4a730793f1eef22b19/neil.gif)
> &ldquo;Yas&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/3)**__
