### ISSUE TITLE
Week 07 Day 2 - Intro to Phaser Games

### ISSUE THREAD

**Issue by gstark** [ooeygg/assignments#24]
## Using a Front End Gaming Library

In this assignment, you'll build a simple game

## Objectives

- Learn a new front end library
- Experiment with writing games

### Explorer Mode

- [x] Get the demo we did in class working locally.
- [x] Play with changing the physics settings in the game to adjust the game play.
- [x] Update the images to your own style.
- [x] Add a new feature to, or change an existing feature of, the game

### Adventure Mode

- [ ] Modify your game to a new game, or create your own!

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Well done!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBWQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--5adeb8e5322994e0cbd1bcd7685cf653f71d406a/giphy-8.gif)
> &ldquo;Well done!&rdquo;
__&mdash; via **[Gavin Stark](https://gifs.suncoast.io/venerations/73)**__
