### ISSUE TITLE
Week 07 Day 4 - Wireframes

### ISSUE THREAD

**Issue by gstark** [ooeygg/assignments#26]
## Build wireframes of your Capstone Project

# Be prepared to show these to your instructor early next week.

**Comment by ooeygg** [comment]
https://github.com/Myenny/crybot

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Ring that bell!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTQT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fabcecd7c921cc4014bfcce0bd127f9e89ef3986/meets-2.gif)
> &ldquo;Ring that bell!&rdquo;
__&mdash; via **[Mark Dewey](https://gifs.suncoast.io/venerations/62)**__
