### ISSUE TITLE
Week 09 Day 1 & 2 - Intro to APIs and ORMS

### ISSUE THREAD

**Issue by mdewey** [ooeygg/assignments#31]
---
title: Take the Safari Online.
draft: true
---

# Let's Continue our safari adventure

We are taking a surprise trip to the Savannah for a safari to see all sorts of exotic animals. During our time their we want to keep track of all the animals we have seen. For this, we need to create an API to help record what we see. 

## Objectives
- Practice Creating Simple APIs
- Practice working with API Tools, such as POSTMAN (https://www.getpostman.com/)

## Requirements
- Using Ruby on Rails or ASP.NET create a simple API for you Safari Database
- Use your language's naming conventions where appropriate. 

### Explorer Mode

* [x] Your database will be named called `SafariVacation` / `safari_vacation`
    * [x] This will have 1 table called `SeenAnimals` / `seen_animals` that has the following columns
        - `Id` / `id` (int)
        - `Species` /  `species` (string)
        - `CountOfTimesSeen` / `count_of_times_seen` (int)
        - `LocationOfLastSeen` / `location_of_last_seen` (string)
    - NOTE: This should be made all in the code (C#/Ruby), and **not** created in the `pgcli`.

* [x] Your API should have the following endpoints:
    - [x] Create `GET /Animals` Endpoint that returns all animals you have seen
    - [x] Create `GET /Search?species=lion` that returns all animals where the species name contains the title parameter
    - [x] Create a `POST /Animal` endpoints that adds a animal to the database. THis should take a JSON body
    - [x] Create a `GET /Animal/{location}` that returns animals of only that location
    - [x] Create a `PUT /Animal/{animal}` endpoint that adds 1 to that animal
    - [ ] Create a `DELETE /Animal/{animal}` endpoint that deletes that animal from the database
 
### Adventure Mode
- [ ] Normalize your database to have `Location` be its own table
- [ ] Extend your `Search` endpoint to search by animal or by location
- [ ] Create a `PUT /Animal/{animal}/{amount}` endpoint that adds `{amount}` to that animal

### Epic Mode
- [ ] Create a React  app that talks to your API and Interacts with all the endpoints
- [ ] Work on your capstone

### .NET 

Here are the interesting commands you will need for tonights assignment

- To get the code gen tools 
```
dotnet tool install --global dotnet-aspnet-codegenerator 
```

- To add Entity Framework to your project: 
``` 
 dotnet add package Microsoft.EntityFrameworkCore.Design 

 dotnet add package Npgsql.EntityFrameworkCore.PostgreSQL 
 ```

 - To create your database:
 ```
 createdb <<DatabaseName>>
 ```

 - To create the DbContext
 ```
 dotnet ef dbcontext scaffold "server=localhost;database=<<DatabaseName>>" Npgsql.EntityFrameworkCore.PostgreSQL -c <<DatabaseName>>Context

```

- Add a migration:
```
 dotnet ef migrations add AddBaordGameTable
```

- Update your database
```
dotnet ef database update  
```

 - Documentation: [Dotnet EF CLI Docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)

**Comment by mdewey** [comment]
Where is your code?

**Comment by mdewey** [comment]
Your homework was marked: **Needs Improvement**

![Run Away](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBFUT09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--6fa0ef90109065a1fcd353f2cd88730836f08cf4/3o7ZeEZUzRjyvWuuIg.gif)
> &ldquo;Run Away&rdquo;
__&mdash; via **[Venel](https://gifs.suncoast.io/venerations/7)**__

**Comment by ooeygg** [comment]
https://github.com/Myenny/SafariVacationAPI
