### ISSUE TITLE
Week 09  Day 3 - Connecting React and API

### ISSUE THREAD

**Issue by mdewey** [ooeygg/assignments#32]
---
title: finish-the-safari
draft: true
---

For this assignment, you should take your safari API that was already created, and create a simple react app that consumes that API. 

## Objectives

* Work with an API that you created

## Requirements

* Create a React app that consumes an API that you created

### Explorer Mode

* [x] Finish all the endpoints from the Safari API
* [x] Create a simple react app, that uses some css make it looks friendly. 
* [x] The react app should:  
    * [x] Display all animals the user has seen
    * [x] Display all animals seen in the `Jungle`
    * [x] Remove all animals that I have seen in the `Desert`. 
    * [ ] Add all the `CountOfTimesSeen` and get a total number of animals seen
    * [ ] Get the `CountOfTimesSeen` of `lions`, `tigers` and `bears`
* [x] The UI is up to you, keep it simple as needed. 
    

### Adventure Mode

* [ ] Work on your capstone app. This weekend, I recommend to focus on your API and Database Schema. 
* [ ] Work on your capstone's HTML, CSS and JS

### .NET 

Here are the interesting commands you will need for tonights assignment

- To add Entity Framework to your project: 
``` 
 dotnet add package Microsoft.EntityFrameworkCore.Design --version 2.1.3

 dotnet add package Npgsql.EntityFrameworkCore.PostgreSQL --version 2.1.2
 ```

 - To create your database:
 ```
 createdb <<DatabaseName>>
 ```

 - To create the DbContext
 ```
 dotnet ef dbcontext scaffold "server=localhost;database=<<DatabaseName>>" Npgsql.EntityFrameworkCore.PostgreSQL -c <<DatabaseName>>Context

```

- Add a migration:
```
 dotnet ef migrations add AddBaordGameTable
```

- Update your database
```
dotnet ef database update  
```

 - Documentation: [Dotnet EF CLI Docs](https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet)

d links shared here.

**Comment by ooeygg** [comment]
https://github.com/Myenny/SafariVacationAPI https://github.com/Myenny/safari

**Comment by mdewey** [comment]
Your homework was marked: **Meets Expectations**

![Gavin Approved!](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBCZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cd97f19100495726ff64a3d09a685c898b2e76b3/gavin-lol.gif)
> &ldquo;Gavin Approved!&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/1)**__
