### ISSUE TITLE
Week 03 Day 2 - Cloudy with a chance of Syntax Error

### ISSUE THREAD

**Issue by gstark** [ooeygg/assignments#9]
Using a popular weather API, Create a web site that allows a user to search for a location and gets that places weather.

## Objectives

- Practice working with an API
- Practice working with data that was structure by a third party

## Requirements

- Using `openweathermap.org`, create a simple UI that allows a user to search for the current weather by zip code or city.

### SIGN UP!

- [x] Visit `openweathermap.org` and signup for an account
- [x] Visit `API Keys` in your dashboard
- [x] Copy your API key
- [x] You can use the API key in any of the URLs by appending `appid=KEY`
  - Example: from the docs `https://api.openweathermap.org/data/2.5/weather?q=Tampa` becomes `https://api.openweathermap.org/data/2.5/weather?q=Tampa&cbb5b6537cd4a6eccd9aee04f4400e4e`
  - NOTE: It will take about 10 to 30 minutes for your API key to be active

### Explorer Mode

- [x] Create a simple HTML page that has a text box and a search `button`
- [x] Allow the user to type in a place, click the search button, and , using `openweathermap.org`, get the current weather for that location.
- [x] Display the weather to user by adding elements to the DOM.
- [x] Allow the user to search by zip or city name.

### Adventure Mode

- [ ] Using the HTML5 Geolocation API, search for the users current location when page loads.
- [ ] Store the Users last search and pull it and search for the value on page load.
- [ ] remove the need for the search button and search when the user stops typing. HINT: use setTimeout and the change event. to track when the user stops typing.

### Epic Mode

- [ ] Add a type a head using Google Places API
- [ ] Head back to blackjack and use [https://deckofcardsapi.com/](https://deckofcardsapi.com/) as your API

**Comment by ooeygg** [comment]
weather-my.surge.sh https://github.com/Myenny/weather

**Comment by gstark** [comment]
Your homework is: Meets Expectations

![Awesome Work!](https://media1.giphy.com/media/csk3GOPxBxUdffDsUV/200w_d.gif)
